
version: "3.8"
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --requirepass localhost
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  database-data: {}
